# Generated by Django 3.1.1 on 2020-09-07 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.TextField()),
                ('unity', models.TextField()),
                ('categoria', models.TextField()),
                ('descricao', models.CharField(max_length=200)),
                ('estoque_atual', models.IntegerField()),
                ('estoque_maximo', models.IntegerField()),
                ('estoque_minimo', models.IntegerField()),
                ('quantidade_por_embalagem', models.IntegerField()),
                ('data_ultima_compra', models.DateTimeField(default=datetime.datetime(2020, 9, 7, 11, 36, 50, 883537))),
                ('ultimo_preço_compra', models.TextField()),
            ],
        ),
    ]
