# Generated by Django 3.1.1 on 2020-09-07 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlEstoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='categoria',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='data_ultima_compra',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 7, 11, 41, 1, 568723)),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='descricao',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='produto',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='unity',
            field=models.CharField(max_length=200),
        ),
    ]
