# Generated by Django 3.1.1 on 2020-09-07 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlEstoque', '0004_auto_20200907_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='data_ultima_compra',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 7, 13, 20, 48, 258380)),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='foto_produto',
            field=models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/'),
        ),
    ]
