# Generated by Django 3.1.1 on 2020-09-08 21:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlEstoque', '0010_auto_20200908_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='foto_produto',
            field=models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='data_ultima_compra',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 8, 18, 38, 9, 140418)),
        ),
        migrations.DeleteModel(
            name='Produtos_loja',
        ),
    ]
