# Generated by Django 3.1.1 on 2020-09-08 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlEstoque', '0011_auto_20200908_1838'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produtos',
        ),
    ]
