# Generated by Django 3.1.1 on 2020-09-08 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlEstoque', '0014_auto_20200908_1914'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produtos',
        ),
    ]
