# Generated by Django 3.1.1 on 2020-09-08 22:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0007_remove_criaadm_cadastro_senha_admin'),
        ('controlEstoque', '0015_delete_produtos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_venda', models.FloatField()),
                ('produto', models.CharField(max_length=200)),
                ('unity', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=200)),
                ('descricao', models.TextField(max_length=200)),
                ('estoque_atual', models.IntegerField()),
                ('estoque_maximo', models.IntegerField()),
                ('estoque_minimo', models.IntegerField()),
                ('quantidade_por_embalagem', models.IntegerField()),
                ('data_ultima_compra', models.DateTimeField(default=datetime.datetime(2020, 9, 8, 19, 21, 9, 894939))),
                ('ultimo_preço_compra', models.IntegerField()),
                ('foto_produto', models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/')),
                ('publicada', models.BooleanField(default=False)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.criaadm')),
            ],
        ),
    ]
