# Generated by Django 3.1.1 on 2020-09-08 22:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlEstoque', '0016_produtos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='data_ultima_compra',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 8, 19, 22, 5, 861285)),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='foto_produto',
            field=models.ImageField(blank=True, upload_to='produtos/%d/%m/%Y/'),
        ),
    ]
