# Generated by Django 3.1.1 on 2020-09-08 23:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlEstoque', '0021_auto_20200908_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='data_ultima_compra',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 8, 20, 38, 25, 332118)),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='foto_produto',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='fotografias/%d/%m/%Y'),
        ),
    ]
