# Generated by Django 3.1.1 on 2020-09-09 21:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_remove_criaadm_cadastro_senha_admin'),
        ('controlEstoque', '0023_auto_20200909_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='data_ultima_compra',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 9, 18, 17, 56, 12557)),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.criaadm'),
        ),
    ]
