# Generated by Django 3.1.1 on 2020-09-09 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlEstoque', '0024_auto_20200909_1817'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produtos',
        ),
    ]
