# Generated by Django 3.1.1 on 2020-09-09 21:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0007_remove_criaadm_cadastro_senha_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('controlEstoque', '0025_delete_produtos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_venda', models.FloatField()),
                ('produto', models.CharField(max_length=200)),
                ('unity', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=200)),
                ('descricao', models.TextField(max_length=200)),
                ('estoque_atual', models.IntegerField()),
                ('estoque_maximo', models.IntegerField()),
                ('estoque_minimo', models.IntegerField()),
                ('quantidade_por_embalagem', models.IntegerField()),
                ('data_ultima_compra', models.DateTimeField(default=datetime.datetime(2020, 9, 9, 18, 22, 14, 809050))),
                ('ultimo_preço_compra', models.IntegerField()),
                ('foto_produto', models.ImageField(blank=True, default=None, null=True, upload_to='fotografias/%d/%m/%Y')),
                ('publicada', models.BooleanField(default=False)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.criaadm')),
                ('vendedor_auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
