# Generated by Django 3.1.1 on 2020-09-10 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlEstoque', '0027_auto_20200910_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='vendedor',
        ),
    ]
