# Generated by Django 3.1.1 on 2020-09-10 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlEstoque', '0029_auto_20200910_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='foto_produto',
            field=models.FileField(blank=True, upload_to='fotografias/%d/%m/%Y'),
        ),
    ]
