# Generated by Django 3.1.1 on 2020-09-11 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlEstoque', '0031_auto_20200910_2042'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produtos',
        ),
    ]
