# Generated by Django 3.1.1 on 2020-09-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlEstoque', '0036_auto_20200917_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='valor_venda',
            field=models.CharField(default='R$0,00', max_length=200),
            preserve_default=False,
        ),
    ]
