# Generated by Django 3.1.1 on 2020-09-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro_Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastro_empresa', models.TextField()),
                ('cadastro_cnpj', models.TextField()),
                ('cadastro_plano', models.TextField()),
                ('cadastro_codigo_autenticacao', models.TextField()),
                ('cadastro_user_admin', models.TextField()),
                ('cadastro_admin_img', models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y')),
                ('cadastro_email_admin', models.TextField()),
                ('cadastro_senha_admin', models.TextField()),
            ],
        ),
    ]
