# Generated by Django 3.1.1 on 2020-09-04 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastro_admin',
            old_name='cadastro_admin_img',
            new_name='img',
        ),
    ]
