# Generated by Django 3.1.1 on 2020-09-04 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20200904_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastro_admin',
            old_name='img',
            new_name='cadastro_admin_img',
        ),
    ]
