# Generated by Django 3.1.1 on 2020-09-04 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20200904_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro_admin',
            name='cadastro_admin_img',
        ),
    ]
