# Generated by Django 3.1.1 on 2020-09-05 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_cadastro_admin_cadastro_admin_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login_Funcionarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionario', models.TextField()),
                ('email', models.TextField()),
                ('pw', models.TextField()),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cadastro_admin')),
            ],
        ),
    ]
