# Generated by Django 3.1.1 on 2020-09-05 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_login_funcionarios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cadastro_Admin',
            new_name='CriaAdm',
        ),
        migrations.RenameModel(
            old_name='Login_Funcionarios',
            new_name='CriaFuncionario',
        ),
    ]
