# Generated by Django 3.1.1 on 2020-09-05 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20200905_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criaadm',
            name='cadastro_senha_admin',
        ),
    ]
